### ISSUE TITLE
Hangs on logging in....

### ISSUE THREAD

**Issue by knuck3ls** [LeonShams/BestBuyBulletBot#1]
Install seemed to go fine. Added test URL in and launched, browser opens and logs in and proceeds to test URL  item and stops. Times out with this:
```
Logging in...
Traceback (most recent call last):
  File "C:\Python\Scripts\3b-bot-script.py", line 33, in <module>
    sys.exit(load_entry_point('3b-bot==0.1.0b1', 'console_scripts', '3b-bot')())
  File "c:\python\lib\site-packages\best_buy_bullet_bot\command_line.py", line 90, in main
    ops[args.COMMAND][0]()
  File "c:\python\lib\site-packages\best_buy_bullet_bot\tracker.py", line 329, in start
    login_cookies_list, predicted_prices, user_agent = login(email, password, urls)
  File "c:\python\lib\site-packages\best_buy_bullet_bot\auto_checkout.py", line 85, in login
    WebDriverWait(driver, USER_TAKEOVER)
  File "c:\python\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```

**Comment by LeonShams** [comment]
If you don't mind, can you send me the URL you added?

**Comment by knuck3ls** [comment]
Sure, I used 2:

https://www.bestbuy.com/site/pokemon-pokemon-tcg-first-partner-collectors-binder/6450052.p?skuId=6450052

https://www.bestbuy.com/site/nvidia-geforce-rtx-nvlink-bridge-for-3090-cards-space-gray/6441554.p?skuId=6441554

**Comment by LeonShams** [comment]
I have updated the source code to solve your issue. Run the following to update to the newer version. Note you may need to reenter your URLs after the update.
```
pip install --upgrade git+https://github.com/LeonShams/BestBuyBulletBot.git
```
Please close the issue if this solves your problem.

**Comment by knuck3ls** [comment]
Close! For tracking purposes would you like this post closed and a new one with the next issue? :)

**Comment by LeonShams** [comment]
Yes!
