### ISSUE TITLE
Best Buy login cookies issue

### ISSUE THREAD

**Issue by bpopov9** [LeonShams/BestBuyBulletBot#19]
--force-login did not execute but showed the error below. I also added the folder login_cookies.json should have been in but was not. Additionally, everytime I started the bot and it opened the new browser, I had to input my credentials into Best Buy even though they have been inputted at set-creds. Is there something I can do to fix this issue? Also why wouldn't login_cookies.json not exist?

![image](https://user-images.githubusercontent.com/79428095/148616539-29b7895c-7f5b-424e-ab4e-2939e11ae855.png)

Windows
3b-bot 1.0.0b3
Python 3.10.1

**Comment by red0fireus** [comment]
I'm having the same issue

**Comment by LeonShams** [comment]
I have resolved the bug causing this error, but I want to clarify precisely what the `--force-login` flag does. By default, the bot will try to log you in with your specified credentials. These credentials are then encrypted and stored locally on your computer. However, if you don't want to go through this process for security or other reasons, you can use the `--force-login` flag, which will open up a browser window and allow you to type in your login information manually.

For most use cases I would recommend running the bot without any additional flags, but if you are interested in doing so, I would recommend taking a look at the [reference sheet](https://bestbuybulletbot.readthedocs.io/en/latest/reference.html) for more information.
