### ISSUE TITLE
Rate Limiting

### ISSUE THREAD

**Issue by Ocean-Moist** [LeonShams/BestBuyBulletBot#3]
Have you run into any ratelimits? I see in your description you mention "Headless item stock tracking (updates up to 100x a second)." 

Wouldn't you get ratelimited pretty quick? I am curious. What is the actual number of times you can track stock per second.

**Comment by LeonShams** [comment]
No, I haven't. I also found it rather odd that I didn't experience any drops, but the connection is steady. I have had it running non-stop for over a week now and haven't had any drops in connection. If anyone does experience any rate-limiting I would be interested to hear about it though.
